"""BYOM test: agent-a2a-connected — direct-client roundtrip.

Proves BYOM prefix survives the A2A protocol hop by:
  1. Provisioning a Prompt Agent with BYOM-routed model (`{gateway}/{model}`).
  2. Attaching an AgentCard via `PATCH /agents/{name}` and enabling
     both `a2a` AND `responses` on `agent_endpoint.protocols`
     (Foundry rejects an a2a-only endpoint with `EndpointProtocolNotEnabled`;
     both protocols are required together — see `_shared.attach_agent_card`).
  3. Sending an A2A JSON-RPC `message/send` with `DefaultAzureCredential`
     (`ai.azure.com` scope; `cognitiveservices` scope 401s server-side).
  4. Polling `tasks/get` until completion and reading the artifact text.

Reply text is generated by the BYOM-prefixed model, so a passing test
means BYOM survived the entire A2A path.
"""
import pytest

from _shared import a2a_send_and_wait, attach_agent_card


@pytest.mark.supported
def test_agent_a2a_connected(project, cfg, static_model, unique_agent_name):
    from azure.ai.projects.models import PromptAgentDefinition

    name = unique_agent_name("byom-a2a-connected")
    try:
        project.agents.create_version(
            agent_name=name,
            definition=PromptAgentDefinition(
                model=static_model(),
                instructions="Reply with a one-sentence summary of the user request. Include the word 'pong'.",
                tools=[],
            ),
        )
        a2a_url = attach_agent_card(cfg, name, enable_protocols=["a2a", "responses"])
        reply = a2a_send_and_wait(a2a_url, "Summarize: the fox jumps over the dog. Reply with 'pong'.", timeout_s=90)
        assert reply and "pong" in reply.lower(), f"unexpected reply: {reply!r}"
    finally:
        try:
            project.agents.delete(agent_name=name, force=True)
        except Exception:
            pass
